language: python
deploy:
  provider: heroku
  api_key:
    secure: Lx8aAwnidiKpM6z5Xizge+KKoeH8xbu0rCofi/DeZ7pEWz4am9DBURlBNCDV6fEYU7ZRXiSNnFsW5MtsR3Fb40N+uYxuXOqcZdv35PoNYv2uEGJRWbLVuw2/pXhCCdB/EZ+zSvAaSKyT7muf42UXGSWZ74uL7WQGszkAlI1/Rp4Llck3HFe/LSYNvgJTHWqHSE/mMQnvM2iwb4LGLnSGmllgsIDhJaWo50yHp1W5kCc0Dep3uT40lnJOPTE5ZLT8iaDU4A/swaTBIfhgUvT4vHJ1jhXa3tr8u0VjjCDLt8cPHFS+t71DeN9eNDbkY2GYperwHYrQkr9FjONzze8BdYJ2L3Batih5NKoBfU+yP7rZ504cwWeqHTnEapPQ/SWfd52CBOoqVZbm/Od4gu6T2Ua0/sI4NKxEiX5XyTwJHID6eOch3WnRYxCoyXTk1nrVpwpWQKDM+LYp89myppC5v8IZd8A8SXkJUynzNIB3iZUIaNaJrBvYi7NVsbXtzHfqSG7q06ZrsRGKnJ3J8c2Mh/081MjFZzOj7SFFWBV21vB7XCiu7FxjVhH7scP8Mk+RzphF3YtFxMjfnAHk6hwYRjo6Hvh/Lawpw1Y7oBUVFbshlgC7yFV7VJNyW1dANcsR9E6zkWlSAqbL9fr+xhzTecKn/BMo5rq3ovvTojLnmQ8=
  app: wciwalks
